### ISSUE TITLE
FakeLogin doesn't work anymore

### ISSUE THREAD

**Issue by AndreasGassmann** [mathewmeconry/bexio#12]
Thanks for this library, it has been working like a charm.

However, a couple of weeks ago it stopped working. We're using the `fakeLogin` and now it always gives us an `Invalid state` error.

It looks to me like the URL that is supposed to contain the code and state is not what it's supposed to be.

`let responseURL = new URL(res.request.href)`

It should probably be something like `/?code=xxx&state=xxx`, but when I print it it's something like `https://my.bexio.com/simplesaml/saml2/idp/SSOService.php?SAMLRequest=xxx`, so it cannot extract the code and state.

Am I the only one with this issue or did Bexio change anything in their login flow?

**Comment by mathewmeconry** [comment]
Hi @AndreasGassmann 

Unfortunately I cannot reproduce your issue with my accounts...
which version of the library do you use? 
can you tell me at which step you printed the url? it would be great if you could give me the exact code you used, that I can try to reproduce your print

**Comment by AndreasGassmann** [comment]
Updating the package solved the problem. I saw it was using a wildcard but forgot that it was locked in the package-lock.json...

Thanks for your help and for the package, keep up the good work 😄

**Comment by mathewmeconry** [comment]
No problem and thanks for the appreciation :)
