### ISSUE TITLE
Failed login for version 3.0

### ISSUE THREAD

**Issue by acharl** [mathewmeconry/bexio#24]
when calling `fakeLogin(username, password)`, it throws `Error: Failed at step 2: do the login` for version 3.0.0 of the API, can anybody confirm?

**Comment by mathewmeconry** [comment]
Hi @acharl 
Have you entered for username and password the credentials for a valid user in your Bexio instance or for the V3.0 API?
This function is meant to fake a login procedure of a real user that we can establish a real server2server interface.

**Comment by acharl** [comment]
@mathewmeconry yes, the provided credentials used to work for the fakeLogin using the previous version of the API, but it seems to fail for the new version. Can you confirm?

**Comment by mathewmeconry** [comment]
@acharl It works for my running project. Have you moved your app to version 3?

**Comment by chuckinSpace** [comment]
The same thing happened to me, I just created the app but the fake login process gets me the same error Failed at step 2: do the login, any info on this?

**Comment by mathewmeconry** [comment]
@chuckinSpace are you using the app credentials of the api v3 or api v2?

**Comment by chuckinSpace** [comment]
v3

**Comment by mathewmeconry** [comment]
these are currently not supported...
I try to find time end of february to implement the first draft of the v3 api

**Comment by mathewmeconry** [comment]
Hey
Better late then never but I published a pre-release for the api v3 implementation. It supports the same endpoints and works with the bexio api tokens for authentication (http://docs.bexio.com/#section/Authentication/API-Tokens)

Release: https://github.com/mathewmeconry/bexio/releases/tag/3.0.0 (not published on npm)

**Comment by mathewmeconry** [comment]
Done with release https://github.com/mathewmeconry/bexio/releases/tag/3.0.0
