### ISSUE TITLE
TypeError: Bexio is not a constructor

### ISSUE THREAD

**Issue by valmiremini** [mathewmeconry/bexio#32]
Hi, 

I get the error "TypeError: Bexio is not a constructor" by Following your example.

```javascript
// import the module
import Bexio from "bexio";

//assign token string
var API_TOKEN = 'my token';

// init the module with the API_TOKEN
const bexio = new Bexio(API_TOKEN);

// show the contact with ID 1 (Promise)
bexio.contacts.show(1).then((contact) => {
  console.log(contact);
});
```

Neat package by the way.

**Comment by mathewmeconry** [comment]
Hi @valmiremini 

Sorry I must have missed the notification...

can you debug the code and check what is in `Bexio`?

**Comment by ItsCoding** [comment]
Same here, it returns 

`{
  BillsStatic: [Getter],
  BusinessActivitiesStatic: [Getter],
  CalendarStatic: [Getter],
  ContactGroupsStatic: [Getter],
  ContactRelationsStatic: [Getter],
  ContactSectorsStatic: [Getter],
  ContactTypesStatic: [Getter],
  ContactsStatic: [Getter],
  ExpensesStatic: [Getter],
  NotesStatic: [Getter],
  OrdersStatic: [Getter],
  ProjectsStatic: [Getter],
  ProjectStatusesStatic: [Getter],
  ProjectTypesStatic: [Getter],
  SalesOrderManagementStatic: [Getter],
  TimetrackingsStatic: [Getter],
  TimetrackingStatusesStatic: [Getter],
  UsersStatic: [Getter],
  ItemsStatic: [Getter],
  default: [class Bexio]
}`

**Comment by mathewmeconry** [comment]
@ItsCoding please send me the import statement and how you try to call the constructor?
It looks like you imported it wrong. or just use `.default` and call the constructor there

**Comment by mathewmeconry** [comment]
Housekeeping
