### ISSUE TITLE
timetracking API

### ISSUE THREAD

**Issue by ktk** [mathewmeconry/bexio#7]
Hi,

First, thanks for the work, looks promising. I wanted to automate some time tracking tasks (really an annoying interface in Bexio). From what I can see this is not yet supported, correct? If so would be happy to test this. Creating a timetracking is what I'm looking for

**Comment by mathewmeconry** [comment]
Hi @ktk 
Yes you're right that the time tracking endpoints are not implemented yet. 
Currently I try to get a test account from Bexio that I don't need to test anything else on my prod account.
After that I'm happy to implement these endpoints

**Comment by ktk** [comment]
@mathewmeconry I created a new org for me, they said that's the preferred way to do it. And if you contact support they will extend it so you don't have to pay for it.

**Comment by mathewmeconry** [comment]
yep they told me the same but until now I only have an account from my organization and not a private one. Additionally they only extend it for 6 months which isn't enough to run automated tests against it in the future.

**Comment by ktk** [comment]
Yeah they really don't get the concept of staging areas... we might have to explain that to them once

**Comment by mathewmeconry** [comment]
Released new endpoints in 0.4.0
